//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_techedEntities : DbContext
    {
        public DB_techedEntities()
            : base("name=DB_techedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAnnouncement> tblAnnouncements { get; set; }
        public virtual DbSet<tblClassCategory> tblClassCategories { get; set; }
        public virtual DbSet<tblClassCourse> tblClassCourses { get; set; }
        public virtual DbSet<tblCourseVideo> tblCourseVideos { get; set; }
        public virtual DbSet<tblEducatorDetail> tblEducatorDetails { get; set; }
        public virtual DbSet<tblEnquiry> tblEnquiries { get; set; }
        public virtual DbSet<tblIdPassword> tblIdPasswords { get; set; }
        public virtual DbSet<tblRefund> tblRefunds { get; set; }
        public virtual DbSet<tblSale> tblSales { get; set; }
        public virtual DbSet<tblSalesReturn> tblSalesReturns { get; set; }
        public virtual DbSet<tblStudentData> tblStudentDatas { get; set; }
        public virtual DbSet<tblTransaction> tblTransactions { get; set; }
        public virtual DbSet<tblTrnMode> tblTrnModes { get; set; }
        public virtual DbSet<CollectionReceivedView> CollectionReceivedViews { get; set; }
        public virtual DbSet<PaymentRefundView> PaymentRefundViews { get; set; }
        public virtual DbSet<SalesReturnView> SalesReturnViews { get; set; }
        public virtual DbSet<SalesView> SalesViews { get; set; }
    }
}
