//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnouncement
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int CourseId { get; set; }
        public string Message { get; set; }
    
        public virtual tblClassCourse tblClassCourse { get; set; }
    }
}
