//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClassCourse()
        {
            this.tblAnnouncements = new HashSet<tblAnnouncement>();
            this.tblCourseVideos = new HashSet<tblCourseVideo>();
            this.tblEnquiries = new HashSet<tblEnquiry>();
            this.tblSales = new HashSet<tblSale>();
            this.tblSalesReturns = new HashSet<tblSalesReturn>();
            this.tblStudentDatas = new HashSet<tblStudentData>();
        }
    
        public int id { get; set; }
        public string CourseName { get; set; }
        public int CourseCategory { get; set; }
        public string BatchInfo { get; set; }
        public Nullable<int> EducatorProfile { get; set; }
        public string CourseDiscription { get; set; }
        public string DetailedDiscription { get; set; }
        public string CourseDuration { get; set; }
        public double CourseFees { get; set; }
        public string CoursePreviewLink { get; set; }
        public Nullable<bool> CourseStatus { get; set; }
        public byte[] CourseImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAnnouncement> tblAnnouncements { get; set; }
        public virtual tblClassCategory tblClassCategory { get; set; }
        public virtual tblEducatorDetail tblEducatorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCourseVideo> tblCourseVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEnquiry> tblEnquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSale> tblSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesReturn> tblSalesReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentData> tblStudentDatas { get; set; }
    }
}
