//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEducatorDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEducatorDetail()
        {
            this.tblClassCourses = new HashSet<tblClassCourse>();
        }
    
        public int id { get; set; }
        public string EducatorName { get; set; }
        public string EducatorProfile { get; set; }
        public string DetailedProfile { get; set; }
        public string EducatorMailId { get; set; }
        public string EducatorMobile { get; set; }
        public byte[] EducatorPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClassCourse> tblClassCourses { get; set; }
    }
}
