//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudentData()
        {
            this.tblRefunds = new HashSet<tblRefund>();
            this.tblSales = new HashSet<tblSale>();
            this.tblSalesReturns = new HashSet<tblSalesReturn>();
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int id { get; set; }
        public string StudentName { get; set; }
        public string StudentMobileNo { get; set; }
        public string StudentMailId { get; set; }
        public string StudentDOB { get; set; }
        public string StudentPAN { get; set; }
        public string StudentAddress { get; set; }
        public string StudentCourseUsername { get; set; }
        public int SubscribedCourseId { get; set; }
        public string StudentLoginPassword { get; set; }
        public bool StudentStatus { get; set; }
    
        public virtual tblClassCourse tblClassCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRefund> tblRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSale> tblSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesReturn> tblSalesReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
